version: "3.8"

services:

  tara-mock:
    container_name: tara-mock
    image: e-gov/tara-mock:latest
    build:
      context: .
      args:
        genkeys: "false"
    ports:
      - "0.0.0.0:8080:8080"